name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # opcional: actualiza métricas cada 12 h

permissions:
  contents: write   # write si quieres commitear metrics.json (opcional)
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Opcional) refresca metrics.json antes de compilar
      - name: Setup Node for metrics script
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Update metrics.json
        run: node scripts/fetch-metrics.js

      # Instala, build y sube el artefacto para Pages
      - name: Install, build and upload
        uses: withastro/action@v4
        with:
          node-version: 20
          path: .

      # (Opcional) persiste el metrics.json en el repo
      - name: Commit metrics (optional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/metrics.json || true
          git commit -m "chore: update metrics [skip ci]" || true
          git push || true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
